CREATE TABLE public.bodega (
    id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    nombre varchar(100) NULL,
    ubicacion varchar(100) NULL,
    CONSTRAINT bodega_pkey PRIMARY KEY (id)
);
CREATE TABLE public.producto (
    id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    nombre varchar(100) NULL,
    categoria int4 NULL,
    CONSTRAINT producto_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inventario (
    id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    producto_id int4 NULL,
    bodega_id int4 NULL,
    cantidad int4 NULL,
    CONSTRAINT inventario_bodega_id_fkey FOREIGN KEY (bodega_id) REFERENCES public.bodega(id),
    CONSTRAINT inventario_producto_id_fkey FOREIGN KEY (producto_id) REFERENCES public.producto(id)
);